# Site settings
title: Nicolas Vaughan
email: <span class="reverse">mail@nicolasvaughan.org</span>
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nicolasvaughan.org" # the base hostname & protocol for your site
gitlab_username:  nivaca

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Associate Professor"
excerpt_separator: "<!--more-->"
